- name: Provision an EC2 Instance
  hosts: local
  connection: local
  gather_facts: False
  tags: provisioning
  vars:
    instance_type: t2.micro
    security_group: basic_access
    image: ami-47c21a25 # Ubuntu Server 16.04 LTS (HVM), SSD Volume Type
    keypair: test-key
    region: ap-southeast-2
    count: 1

  tasks:
    - name: Create a key pair
      ec2_key:
          name: "{{ keypair }}"
          region: "{{ region }}"
      register: ec2_key

    - name: Save private key
      copy: content="{{ ec2_key.key.private_key }}" dest="./aws-private.pem" mode=0600
      when: ec2_key.changed

    - name: Create a security group
      ec2_group: 
        name: "{{ security_group }}"
        description: a basic security group
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Launch the new EC2 Instance
      ec2:
        group: "{{ security_group }}"
        instance_type: "{{ instance_type}}"
        image: "{{ image }}"
        wait: "true"
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        instance_tags:
          testserver: yes
        count_tag: testserver
        exact_count: "{{ count }}"
      register: ec2

    - name: Add the newly created EC2 instance(s) to the host
      lineinfile:
        dest: "./hosts" 
        regexp: "{{ item.public_ip }}"
        insertafter: "[testserver]" 
        line: "{{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22 
        timeout: 240 
        state: started
      with_items: "{{ ec2.instances }}"
