- name: Configure the created ec2 instance
  hosts: testserver
  remote_user: ubuntu
  become: yes
  gather_facts: no
  pre_tasks:
  - name: "install python"
    raw: "sudo apt update && sudo apt install -y python python-pip"
  - name: "pip install docker"
    raw: "pip install docker"

  tasks:
  - name: "Firewass settings"
    shell: |
      sudo ufw default deny incoming
      sudo ufw default allow outgoing
      sudo ufw allow 22
      sudo ufw allow 80

  - name: "Install Docker CE"
    shell: |
      sudo apt install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
      sudo apt update
      sudo apt -y install docker-ce

  - name: "Deploy and start an nginx container in docker"
    docker_container:
      name: nginx_server
      image: nginx
      state: started
      ports:
      - "80:80"

  - name: "Run a command to test the healthiness of the nginx container"
    uri:
      url: "http://localhost"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 120
    delay: 2

  - name: "Fetch the output of the nginx container’s default http page"
    get_url:
      url: http://localhost
      dest: /tmp/index.html

  - name: "Print out the word that occurs most on the page"
    copy:
      src: ./word_count.py
      dest: ~/word_count.py

  - name: "Print"
    shell: python ~/word_count.py /tmp/index.html
    register: count

  - debug: msg="{{ count.stdout }}"